spring.application.name=beautyparlour
server.port=8081
# Enable H2 console for testing database structures if needed (optional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Disable Hibernate schema validation errors by updating schemas automatically
spring.jpa.hibernate.ddl-auto=update
